refactor: update Vencord update process
- Replaced the shell script for updating Vencord with
`passthru.updateScript`
- Removed obsolete update scripts for Discord and Vencord

diff --git a/.github/workflows/update-vencord.yaml b/.github/workflows/update-vencord.yaml
--- a/.github/workflows/update-vencord.yaml
+++ b/.github/workflows/update-vencord.yaml
@@ -40,10 +40,16 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          if ! ./pkgs/update-vencord.sh unstable pkgs/vencord.nix; then
-            echo "Failed to update Vencord"
+          if ! nix build --impure --expr 'let pkgs = import <nixpkgs> {}; in (pkgs.callPackage ./pkgs/vencord.nix { unstable = true; }).passthru.updateScript'; then
+            echo "Failed to build the update script."
             exit 1
           fi
+          if ! ./result/bin/vencord-update unstable; then
+            echo "Update script failed to execute successfully"
+            exit 1
+          fi
+          echo "Vencord update script finished."
+          rm ./result
 
       - name: Get new version
         id: new-version
@@ -116,10 +122,16 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          if ! ./pkgs/update-vencord.sh stable pkgs/vencord.nix; then
-            echo "Failed to update Vencord"
+          if ! nix build --impure --expr 'let pkgs = import <nixpkgs> {}; in (pkgs.callPackage ./pkgs/vencord.nix { unstable = false; }).passthru.updateScript'; then
+            echo "Failed to build the update script."
             exit 1
           fi
+          if ! ./result/bin/vencord-update stable; then
+            echo "Update script failed to execute successfully"
+            exit 1
+          fi
+          echo "Vencord update script finished."
+          rm ./result
 
       - name: Get new version
         id: new-version
