chore: move all pkgs to `pkgs/`

diff --git a/.github/workflows/update-discord.yaml b/.github/workflows/update-discord.yaml
--- a/.github/workflows/update-discord.yaml
+++ b/.github/workflows/update-discord.yaml
@@ -54,7 +54,7 @@ jobs:
         env:
           NIXPKGS_ALLOW_UNFREE: 1
         run: |
-          if ! nix build --impure --expr 'let pkgs = import <nixpkgs> { config.allowUnfree = true; }; in (pkgs.callPackage ./discord.nix {}).passthru.updateScript'; then
+          if ! nix build --impure --expr 'let pkgs = import <nixpkgs> { config.allowUnfree = true; }; in (pkgs.callPackage ./pkgs/discord.nix {}).passthru.updateScript'; then
             echo "Failed to build the update script."
             exit 1
           fi
@@ -69,8 +69,8 @@ jobs:
         id: new-versions
         shell: bash
         run: |
-          if [[ ! -f discord.nix ]]; then
-            echo "discord.nix not found after update script ran"
+          if [[ ! -f ./pkgs/discord.nix ]]; then
+            echo "pkgs/discord.nix not found after update script ran"
             exit 1
           fi
           perl_output=$(perl -ne '
@@ -80,7 +80,7 @@ jobs:
             if ($platform && /^\s*(stable|ptb|canary|development)\s*=\s*"([^"]+)";/) {
               print "OUTPUT_VAR:${platform}_$1=$2\n";
             }
-          ' discord.nix)
+          ' pkgs/discord.nix)
 
           while IFS= read -r line; do
              line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
@@ -101,7 +101,7 @@ jobs:
           set -e
           for branch in stable ptb canary development; do
             echo "Testing build for $branch"
-            if ! nix-build --arg config '{ allowUnfree = true; }' -E "let pkgs = import <nixpkgs> {}; in pkgs.callPackage ./discord.nix { branch = \"$branch\"; }"; then
+            if ! nix-build --arg config '{ allowUnfree = true; }' -E "let pkgs = import <nixpkgs> {}; in pkgs.callPackage ./pkgs/discord.nix { branch = \"$branch\"; }"; then
                echo "Failed to build $branch"
                exit 1
             fi
@@ -163,8 +163,8 @@ jobs:
           commit_body=$(echo -e "$commit_body" | sed '/^$/d' | sed '$ s/\\n$//')
           COMMIT_MSG="discord: update versions\n\n$commit_body"
 
-          if [[ -n "$(git status --porcelain discord.nix)" ]]; then
-            git add discord.nix
+          if [[ -n "$(git status --porcelain pkgs/discord.nix)" ]]; then
+            git add pkgs/discord.nix
             # Use printf to handle multi-line message correctly
             printf "%b" "$COMMIT_MSG" | git commit -F -
 
@@ -181,5 +181,5 @@ jobs:
               sleep 5
             done
           else
-            echo "`git status` shows no changes to `discord.nix`. Skipping commit"
+            echo "`git status` shows no changes to `pkgs/discord.nix`. Skipping commit"
           fi
